"""Configuration and constants for Lakeventory."""

SHEET_ORDER = [
    "Notebooks",
    "Workspace Objects",
    "Jobs Runs",
    "Clusters Pools Policies",
    "SQL Warehouses",
    "SQL Dashboards Queries",
    "MLflow",
    "Unity Catalog",
    "External Locations",
    "Repos Git",
    "Secrets Tokens IP",
    "Identities",
    "Serving Vector Online",
    "Sharing",
    "DBFS",
]

KIND_TO_SHEET = {
    "workspace_dir": "Workspace Objects",
    "workspace_notebook": "Notebooks",
    "workspace_file": "Workspace Objects",
    "job": "Jobs Runs",
    "job_run": "Jobs Runs",
    "cluster": "Clusters Pools Policies",
    "instance_pool": "Clusters Pools Policies",
    "cluster_policy": "Clusters Pools Policies",
    "global_init_script": "Clusters Pools Policies",
    "instance_profile": "Clusters Pools Policies",
    "sql_warehouse": "SQL Warehouses",
    "sql_dashboard": "SQL Dashboards Queries",
    "lakeview_dashboard": "SQL Dashboards Queries",
    "sql_query": "SQL Dashboards Queries",
    "sql_alert": "SQL Dashboards Queries",
    "sql_alert_v2": "SQL Dashboards Queries",
    "mlflow_experiment": "MLflow",
    "mlflow_model": "MLflow",
    "model_version": "MLflow",
    "uc_catalog": "Unity Catalog",
    "uc_schema": "Unity Catalog",
    "uc_table": "Unity Catalog",
    "uc_volume": "Unity Catalog",
    "external_location": "External Locations",
    "storage_credential": "External Locations",
    "connection": "External Locations",
    "metastore": "External Locations",
    "repo": "Repos Git",
    "git_credential": "Repos Git",
    "secret_scope": "Secrets Tokens IP",
    "token": "Secrets Tokens IP",
    "ip_access_list": "Secrets Tokens IP",
    "user": "Identities",
    "group": "Identities",
    "service_principal": "Identities",
    "serving_endpoint": "Serving Vector Online",
    "vector_search_endpoint": "Serving Vector Online",
    "vector_search_index": "Serving Vector Online",
    "online_table": "Serving Vector Online",
    "share": "Sharing",
    "recipient": "Sharing",
    "provider": "Sharing",
    "dbfs_dir": "DBFS",
    "dbfs_file": "DBFS",
}
